apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-bot
  labels:
    {{- include "emojivoto.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-bot
  template:
    metadata:
      labels:
        app: vote-bot
        version: {{ .Values.image.tag }}
    spec:
      containers:
      - command:
        - emojivoto-vote-bot
        env:
        - name: WEB_HOST
          value: web-svc:80
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}-web
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: vote-bot
        resources:
          requests:
            cpu: 10m