kind: ServiceAccount
apiVersion: v1
metadata:
  name: web
  labels:
    {{- include "emojivoto.labels" . | nindent 4 }}
# Todo: From when Preview injects imagePullSecrets appropriately
imagePullSecrets:
  - name: previewhq-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    {{- include "emojivoto.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-svc
  template:
    metadata:
      labels:
        app: web-svc
        version: {{ .Values.image.tag }}
    spec:
      serviceAccountName: web
      containers:
      - env:
        - name: WEB_PORT
          value: "8080"
        - name: EMOJISVC_HOST
          value: emoji-svc:8080
        - name: VOTINGSVC_HOST
          value: voting-svc:8080
        - name: INDEX_BUNDLE
          value: dist/index_bundle.js
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}-web
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: web-svc
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  labels:
    {{- include "emojivoto.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: web-svc
  ports:
  - name: http
    port: 80
    targetPort: 8080